[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn assessment_v3.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
